// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqJSaZABTLzk8HLCEfeVEphJ3JMjN_25s',
    appId: '1:1002961369822:web:45c73a2397ac8dea49a04f',
    messagingSenderId: '1002961369822',
    projectId: 'gotrip-72431',
    authDomain: 'gotrip-72431.firebaseapp.com',
    storageBucket: 'gotrip-72431.appspot.com',
    measurementId: 'G-N7PSYB05R7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9cE5yUiTT-wxtTy1ulEn45sBLP5dVpWI',
    appId: '1:1002961369822:android:9d967a3727b16cd849a04f',
    messagingSenderId: '1002961369822',
    projectId: 'gotrip-72431',
    storageBucket: 'gotrip-72431.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ08XeLWREUC_lWkfWHXbHJLJHcqjW7WE',
    appId: '1:1002961369822:ios:4aa7460e8d987a2a49a04f',
    messagingSenderId: '1002961369822',
    projectId: 'gotrip-72431',
    storageBucket: 'gotrip-72431.appspot.com',
    iosBundleId: 'com.example.travel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJ08XeLWREUC_lWkfWHXbHJLJHcqjW7WE',
    appId: '1:1002961369822:ios:2893761b06d0550a49a04f',
    messagingSenderId: '1002961369822',
    projectId: 'gotrip-72431',
    storageBucket: 'gotrip-72431.appspot.com',
    iosBundleId: 'com.example.travel.RunnerTests',
  );
}
